version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: diario_copa_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: db_diariocopa
      MYSQL_USER: user_copa
      MYSQL_PASSWORD: senha_copa_123
    ports:
      - "11000:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  api-diariocopa:
    build: 
      context: ./DiarioCopaApi
    container_name: diario_copa_api
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    environment:
      - ConnectionStrings__DefaultConnection=Server=mysql-db;Port=3306;Database=db_diariocopa;Uid=user_copa;Pwd=senha_copa_123;
      - ASPNETCORE_ENVIRONMENT=Development
volumes:
  mysql_data: