// <auto-generated />
using System;
using DiarioCopaApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiarioCopaApi.Migrations
{
    [DbContext(typeof(DiarioCopaContext))]
    [Migration("20260604231902_FixRelacionamentos")]
    partial class FixRelacionamentos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DiarioCopaApi.Models.Experiencia", b =>
                {
                    b.Property<Guid>("IdExperiencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Assistido")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Comentario")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Favorito")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("IdJogo")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("char(36)");

                    b.Property<string>("Localizacao")
                        .HasColumnType("longtext");

                    b.Property<int?>("Nota")
                        .HasColumnType("int");

                    b.Property<int?>("Sentimento")
                        .HasColumnType("int");

                    b.Property<string>("URL_Imagem")
                        .HasColumnType("longtext");

                    b.HasKey("IdExperiencia");

                    b.HasIndex("IdJogo");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Experiencias");
                });

            modelBuilder.Entity("DiarioCopaApi.Models.Jogo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Estadio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Fase")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int?>("GolsTime1")
                        .HasColumnType("int");

                    b.Property<int?>("GolsTime2")
                        .HasColumnType("int");

                    b.Property<string>("Time1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Time2")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Jogos");
                });

            modelBuilder.Entity("DiarioCopaApi.Models.JogoFavorito", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IdJogo")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.HasKey("IdUsuario", "IdJogo");

                    b.HasIndex("IdJogo");

                    b.ToTable("JogosFavoritos");
                });

            modelBuilder.Entity("DiarioCopaApi.Models.ListaJogos", b =>
                {
                    b.Property<Guid>("IdLista")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("char(36)");

                    b.Property<string>("TituloLista")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdLista");

                    b.HasIndex("IdUsuario");

                    b.ToTable("ListasJogos");
                });

            modelBuilder.Entity("DiarioCopaApi.Models.Usuario", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("HashSenha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("JogoListaJogos", b =>
                {
                    b.Property<Guid>("JogosId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ListaJogosIdLista")
                        .HasColumnType("char(36)");

                    b.HasKey("JogosId", "ListaJogosIdLista");

                    b.HasIndex("ListaJogosIdLista");

                    b.ToTable("ListaJogosJogos", (string)null);
                });

            modelBuilder.Entity("DiarioCopaApi.Models.Experiencia", b =>
                {
                    b.HasOne("DiarioCopaApi.Models.Jogo", "Jogo")
                        .WithMany()
                        .HasForeignKey("IdJogo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiarioCopaApi.Models.Usuario", "Usuario")
                        .WithMany("Experiencias")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DiarioCopaApi.Models.JogoFavorito", b =>
                {
                    b.HasOne("DiarioCopaApi.Models.Jogo", "Jogo")
                        .WithMany()
                        .HasForeignKey("IdJogo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiarioCopaApi.Models.Usuario", "Usuario")
                        .WithMany("JogoFavorito")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DiarioCopaApi.Models.ListaJogos", b =>
                {
                    b.HasOne("DiarioCopaApi.Models.Usuario", "Usuario")
                        .WithMany("ListaJogos")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("JogoListaJogos", b =>
                {
                    b.HasOne("DiarioCopaApi.Models.Jogo", null)
                        .WithMany()
                        .HasForeignKey("JogosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiarioCopaApi.Models.ListaJogos", null)
                        .WithMany()
                        .HasForeignKey("ListaJogosIdLista")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiarioCopaApi.Models.Usuario", b =>
                {
                    b.Navigation("Experiencias");

                    b.Navigation("JogoFavorito");

                    b.Navigation("ListaJogos");
                });
#pragma warning restore 612, 618
        }
    }
}
