FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ["DiarioCopaApi.csproj", "./"]
RUN dotnet restore "./DiarioCopaApi.csproj"

COPY . .
RUN dotnet publish "DiarioCopaApi.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
EXPOSE 8080

COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "DiarioCopaApi.dll"]